package com.gaia3d.command;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum CommandOptions {
    // Default options
    HELP("help", "h", false, "Print help"),
    QUIET("quiet", "q", false, "Suppress all output except errors"),
    LEAVE_TEMP("leaveTemp", "lt", false, "Leave temporary files for debugging"),
    JSON("json", "j", false, "Generate layer.json for terrain data"),
    SKIP_STANDARDIZATION_RESIZE("skipStandardizationResize", "ssr", false, "Skip standardization and resizing process. This option can be used when the input data is already standardized and resized."),
    // Path options
    INPUT("input", "i", true, "[Required] Input file or directory path. Repeatable."),
    OUTPUT("output", "o", true, "[Required] Output directory path"),
    LOG("log", "l", true, "Log file path"),
    TEMP_PATH("temp", "t", true, "Temporary directory path (default: {OUTPUT}/temp)"),
    GEOID_PATH("geoid", "g", true, "Set the height reference for terrain data. \n"
            + "Geoid file path for height correction. \n(default: Ellipsoid)(options: Ellipsoid, EGM96, EGM2008, EGM84, or GeoTIFF file path)"),

    // Terrain generation options
    MINIMUM_TILE_DEPTH("minDepth", "min", true, "Set the minimum terrain tile depth. This is effectively fixed at 0. \n(default: 0)(options: 0 - 22)"),
    MAXIMUM_TILE_DEPTH("maxDepth", "max", true, "Set the maximum terrain tile depth. If omitted, it is calculated automatically from the input raster resolution. \n(options: 0 - 22)"),
    INTENSITY("intensity", "is", true, "Set the mesh refinement intensity. \n(default: 4.0)"),
    INTERPOLATION_TYPE("interpolationType", "it", true, "Set the interpolation type. \n(default: bilinear)(options: nearest, bilinear)"),
    PRIORITY_TYPE("priorityType", "pt", true, "Set the height priority for overlapping terrain data. \n(default: resolution)(options: resolution, higher)"),
    NODATA_VALUE("nodataValue", "nv", true, "Set the NODATA value for terrain generation. \n(default: -9999)"),
    EXT_CALCULATE_NORMALS("calculateNormals", "cn", false, "[Deprecated] Terrain octVertexNormals are generated by default."),
    EXT_NO_CALCULATE_NORMALS("noCalculateNormals", "ncn", false, "Disable generation of terrain octVertexNormals."),

    // Optimization options
    TILING_MOSAIC_SIZE("mosaicSize", "ms", true, "Set the tiling mosaic buffer size per tile. \n(default: 8)"),
    RASTER_MAXIMUM_SIZE("rasterMaxSize", "mr", true, "Set the maximum raster size for splitting. \n(default: 4096)"),

    // Experimental options
    CONTINUOUS("continue", "c", false, "[Experimental] Continue terrain generation from the previous run. Use this option when terrain generation is interrupted or fails."),
    MODIFY("modify", "m", false, "[Experimental] Modify existing terrain. Use this option when updating part of a terrain region."),
    EXT_META_DATA("metadata", "md", false, "[Experimental] Generate metadata for terrain data."),
    EXT_WATER_MASK("waterMask", "wm", false, "[Experimental] Generate a water mask for terrain data."),
    //INPUT_CRS("inputCrs", "ic", true, "[Experimental] Input Coordinate Reference System, EPSG Code [4326, 3857...]"),
    //TILING_SCHEMA("tilingSchema", "ts", true, "[Experimental] Schema for the terrain data. [geodetic, mercator][default : geodetic]"),

    /* Celestial Body Option */
    BODY("body", "b", true, "Set the celestial body for terrain generation. \n(default: earth)(options: earth, moon)"),

    /* Debug Options */
    VERBOSE("verbose", "vb", false, "Print verbose logs."),
    DEBUG("debug", "d", false, "[DEBUG] Print more detailed logs.");

    private final String longName;
    private final String shortName;
    private final boolean argRequired;
    private final String description;

    public static CommandOptions[] getAllOptions() {
        return CommandOptions.values();
    }
}
