import org.gradle.internal.os.OperatingSystem

subprojects {
    group "com.gaia3d"
    version "1.0.0"
    apply plugin: 'java'

    repositories {
        maven { url "https://repo.osgeo.org/repository/release/" }
        mavenCentral()
    }

    dependencies {

    }
}

project(':mago-common') {
    // Common module
}

project(':air-pollution') {
    // Extension module build configuration
    dependencies {
        implementation project(':mago-common')
    }
}

